#example
redis:
  host: "127.0.0.1:6379"
  password: "admin"
  db: 0

udp:
  pkg_limit_rfc1035: 512
  pkg_limit_edns0: 4096

server:
  port: 2053
  protocol: "udp"
  #  workers: 4
  event_queue_size: 1000
  event_queue_timeout_milliseconds: 500
  cache_ttl_seconds: 300
